### ISSUE TITLE
Fails to compile on mainnet-1.2.5 version currently used 

### ISSUE THREAD

**Issue by eluzgin** [EOSLaoMao/elasticsearch_plugin#1]
I received compilation error when trying to compile against Mainnet-1.2.5 tag currently used by BPs on Mainnet (https://github.com/EOS-Mainnet/eos): 

/opt/eos/plugins/elasticsearch_plugin/elasticsearch_plugin.cpp:294:15: error: no member named 'producer_block_id' in 'eosio::chain::transaction_trace'
      if( !t->producer_block_id.valid() )
           ~  ^

I will attempt against EOSIO master version as well.

**Comment by WLBF** [comment]
> I received compilation error when trying to compile against Mainnet-1.2.5 tag currently used by BPs on Mainnet (https://github.com/EOS-Mainnet/eos):
> 
> /opt/eos/plugins/elasticsearch_plugin/elasticsearch_plugin.cpp:294:15: error: no member named 'producer_block_id' in 'eosio::chain::transaction_trace'
> if( !t->producer_block_id.valid() )
> ~ ^
> 
> I will attempt against EOSIO master version as well.

Currently the plugin only work with [official eosio repository](https://github.com/EOSIO/eos).
